### ISSUE TITLE
`planner.plan`错误

### ISSUE THREAD

**Issue by nizq** [kcl-lang/kcl-py#34]
### 1. Minimal reproduce step (Required)

```py
import kclvm.program.exec as kclvm_exec
import kclvm.vm.planner as planner

def main():    
    result = kclvm_exec.Run(["main.k"])
    print(planner.plan(result.filter_by_path_selector()))
```

### 2. What did you expect to see? (Required)

```yaml
The_first_kcl_program: Hello World!
```

### 3. What did you see instead (Required)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nizq/workspace/gitee/easyoss/easyops/easyops/cli.py", line 20, in main
    planner.YAMLPlanner().plan(result.filter_by_path_selector())
  File "/home/nizq/.cache/pypoetry/virtualenvs/easyops-e3l7Kj-s-py3.11/lib/python3.11/site-packages/kclvm/vm/planner/plan.py", line 240, in plan
    plan_obj = super().plan(var_dict) if to_py else var_dict
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nizq/.cache/pypoetry/virtualenvs/easyops-e3l7Kj-s-py3.11/lib/python3.11/site-packages/kclvm/vm/planner/plan.py", line 224, in plan
    return [self.plan_dict(v) for v in var]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nizq/.cache/pypoetry/virtualenvs/easyops-e3l7Kj-s-py3.11/lib/python3.11/site-packages/kclvm/vm/planner/plan.py", line 224, in <listcomp>
    return [self.plan_dict(v) for v in var]
            ^^^^^^^^^^^^^^^^^
  File "/home/nizq/.cache/pypoetry/virtualenvs/easyops-e3l7Kj-s-py3.11/lib/python3.11/site-packages/kclvm/vm/planner/plan.py", line 212, in plan_dict
    return {
           ^
  File "/home/nizq/.cache/pypoetry/virtualenvs/easyops-e3l7Kj-s-py3.11/lib/python3.11/site-packages/kclvm/vm/planner/plan.py", line 215, in <dictcomp>
    if v and v.type() in KCL_PLAN_TYPE
             ^^^^^^
AttributeError: 'str' object has no attribute 'type'

```

### 4. What is your KCL components version? (Required)

```
kclvm-0.8.0
```

### 5. 其它

参考`kcl-py/kclvm/internal/kclvm_internal/main.py`，将代码改为:

```py
import kclvm.program.exec as kclvm_exec
import kclvm.vm.planner as planner

def main():    
    result = kclvm_exec.Run(["main.k"])
    print(planner.YAMLPlanner().plan(result.filter_by_path_selector(), to_py=False))
```
则工作正常。

**Comment by Peefy** [comment]
Thank you for your feedback. The fixed code will be released in version 0.8.0.2.
